# Generated by Django 5.0.3 on 2024-04-02 18:55

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_users', '0005_alter_botuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark_img', models.ImageField(default='/core/photo_editing/static/watermarks/logo3.png', storage=django.core.files.storage.FileSystemStorage(base_url='/static', location='/core/photo_editing/static'), upload_to='watermarks/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_users.botuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Watermark',
                'verbose_name_plural': 'Users Watermarks',
            },
        ),
    ]
