# Generated by Django 5.0.3 on 2024-04-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_editing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermarkmodel',
            name='watermark_img',
            field=models.ImageField(default='/photo_editing/watermarks/logo3.png', upload_to='photo_editing/watermarks/', verbose_name='Watermark Image'),
        ),
    ]
