# Generated by Django 5.0.3 on 2024-03-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='user_last_loc_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='user_last_loc_lon',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='user_last_loc_name',
            field=models.CharField(null=True),
        ),
    ]
