# Generated by Django 5.0.3 on 2024-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0002_botuser_user_last_loc_lat_botuser_user_last_loc_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registration date'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_firstname',
            field=models.CharField(verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_last_loc_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Last located latitude'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_last_loc_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Last located longitude'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_last_loc_name',
            field=models.CharField(blank=True, null=True, verbose_name='Last located city'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_lastname',
            field=models.CharField(blank=True, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_username',
            field=models.CharField(verbose_name='Username'),
        ),
    ]
