# Generated by Django 5.0.3 on 2024-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_users', '0004_alter_botuser_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='User ID'),
        ),
    ]
